### ISSUE TITLE
Feature Request: Add channel override support

### ISSUE THREAD

**Issue by RobertHunter-Pluto** [TheAppleFreak/winston-slack-webhook-transport#18]
Could the option for overriding the default webhook channel be supported? Slack added this somewhat recently I think in their webhook API options, all you have to do is specify a `channel: ${your channel here}` in the JSON payload. 

If you're accepting PR's, I would be happy to submit one.

**Comment by TheAppleFreak** [comment]
Yeah, that's definitely something I can add! If you want to submit a PR, that'd be really appreciated.

**Comment by TheAppleFreak** [comment]
Ah, sorry, I took another look at the docs, [and it doesn't look like Slack supports that](https://api.slack.com/messaging/webhooks#advanced_message_formatting) (it's at the end of this section). I thought this was the case, as when I bumped the version to 2.0.0 they had removed those options from the API, but your message suggested they put it back in. 

Thanks for the suggestion regardless!

**Comment by RobertHunter-Pluto** [comment]
Hmmm, I wonder if the slack docs are out of date. I tested it on a current slack webhooks integration and it works as intended, and when you setup a webhook integration inside of your slack app, there's actually a separate set of setup instructions that specify if does work, here's a screenshot since I can't share a link to my specific integration.

![image](https://user-images.githubusercontent.com/79473779/166263166-659a9ea5-574a-47da-9e54-7c6803bb2d96.png)

Unless I somehow have an older version of the integration on my slack app that has yet to be updated.
