### ISSUE TITLE
AttachmentsFormatter function

### ISSUE THREAD

**Issue by FredericLatour** [TheAppleFreak/winston-slack-webhook-transport#2]
What do you think of allowing for an attachment formatter function?
The reason is that having meta information formatted as an attachment is not necessarily great for other transports (file, console, etc ...).
By having an attachmentFormatter (or transformer whatever name you prefer) function, it would be possible to convert the generic meta information into attachment just for slack.

```javascript
    if (this.attachmentFormatter && typeof this.attachmentFormatter === 'function') {
      payload.attachments = this.attachmentFormatter(info)
    } else {
      // for compatibility with the way it currently works
      let attachments = []
      let attachmentKeys = Object.keys(info).filter(key => !isNaN(parseInt(key)))
      attachmentKeys.forEach(key => attachments.push(info[key]))
      payload.attachments = attachments
    }
```

**Comment by TheAppleFreak** [comment]
That sounds like a good idea! This was an issue that I was mulling pretty recently, actually, but it never crossed my mind to use something like a formatter function. I'll integrate that when I get a chance.

**Comment by TheAppleFreak** [comment]
Well, it took a bit for me to remember to do this, but that's now been implemented! It's a breaking change, but it's for the best in the long term.
